version: '3.8'

services:
  notify-api:
    container_name: briohr-notify-api
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - .:/usr/src/app
    restart: unless-stopped
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    container_name: mongodb.local
    ports:
      - 27017:27017
    restart: unless-stopped
  mockoon:
    container_name: briohr-notify-mockoon
    build:
      context: .
      dockerfile: ./mockoon.Dockerfile
    ports:
      - 3003:3003
    volumes:
      - .:/usr/src/app
    restart: unless-stopped