version: '3.8'

services:
  notify-api:
    container_name: briohr-notify-api
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
      - 9229:9229
    networks:
      - briohr-network
    volumes:
      - .:/usr/src/app
    restart: unless-stopped
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 27017:27017
    networks:
      - briohr-network
    restart: unless-stopped

networks:
  briohr-network: